- cmd/baseapp/main.go
- network/client.go
- rpcclient/client.go
- rpcclient/optimism/client.go
- sequencer/sequencer.go
Closes: #345 
---
- @kashishshah
> fix: get rid of logging

- consensus/types/round_state.go
- sequencer/types/v2/batch.go
Closes: #342
---
- @kashishshah
> fix the batch to avoid nil pointer access

- cmd/baseapp/main.go
- consensus/types/round_state.go
- network/client.go
- rpcclient/client.go
- rpcclient/evmclient/evmclient.go
- rpcclient/optimism/batch_fetcher.go
- rpcclient/optimism/client.go
- rpcclient/optimism/client_test.go
- rpcclient/types/interface.go
- sequencer/sequencer.go
- sequencer/types/v2/batch.go
- testutil/operations/manager.go
- Get rid of the sensitive config logging
- Fix the nil pointer access in the consensus module
- Fix to avoid the fatal in the batch fetcher logic
> release v0.3.x alpha

- network/client.go
- rpcclient/client.go
Closes: #356 
---
- @mastereng12
> avoid the panic of wrong chain name

- consensus/state.go
- network/client.go
- network/service.go
Closes: #352
---
- @cool-develope
- @kashishshah
> add more combinient logs

- network/client_test.go
- rpcclient/optimism/batch_decoder.go
- rpcclient/optimism/batch_fetcher.go
- rpcclient/optimism/client.go
Closes: #355 
---
- @kashishshah
> fix: panic in the fetcher

- Makefile
- crypto/keystore.go
- docker-compose.yml
- minor updates to avoid the mismatch
- @cool-develope
> chore: minor change in the crypto curve

- .github/CODEOWNERS
- .github/pull_request_template.md
- .github/workflows/test.yml
> chore: add the code owners

- config/config.go
- config/config_test.go
Closes: #380 
---
- @mastereng12
> chore: check the wrong config path

- consensus/state.go
- consensus/types/round_state.go
- network/client.go
> chore: add more metrics on consensus

- crypto/keystore_test.go
> chore: add more tests of keystore loading

- rpcclient/arbitrum/batch_fetcher.go
- rpcclient/arbitrum/client.go
- rpcclient/evmclient/evm_test.go
- rpcclient/evmclient/evmclient.go
- rpcclient/optimism/client_test.go
- rpcclient/types/interface.go
- sequencer/sequencer.go
Closes: #398
---
- @kashishshah
> feat: update the evmclient to speed up L2 block fetching

- config/default.go
- consensus/state.go
- consensus/state_test.go
- network/interfaces.go
- network/service.go
- network/service_test.go
- testutil/operations/manager.go
> fix: data race on the consensus

- rpcclient/optimism/batch_fetcher.go
> chore: fix deadlock on the optimism rpc client

- network/client.go
- rpcclient/arbitrum/batch_fetcher.go
- rpcclient/arbitrum/client.go
- rpcclient/optimism/batch_fetcher.go
- rpcclient/optimism/client.go
Closes: #410 
---
- @kashishshah
> refactor: the client store logic 

- rpcclient/arbitrum/batch_fetcher.go
- rpcclient/arbitrum/sequencer_inbox.go
- rpcclient/evmclient/evmclient.go
- rpcclient/mantle/client.go
- rpcclient/optimism/batch_fetcher.go
- rpcclient/types/interface.go
- utils/context.go
> chore: avoid the ctx stuck in the RPC call

- network/client.go
- network/health.go
ref: #414
---
- @cool-develope
- @kashishshah
> grpc request with timeout context

- network/client.go
- tests/integration/client_test.go
> fix: error propogation in JoinNetwork

- network/client.go
- network/client_test.go
- rpcclient/arbitrum/batch_fetcher.go
- rpcclient/arbitrum/client.go
- rpcclient/optimism/batch_decoder.go
- rpcclient/optimism/batch_fetcher.go
- rpcclient/optimism/client.go
- store/goleveldb/db.go
- store/goleveldb/db_test.go
> test: add more client storage tests

- network/client.go
Closes: #XXXX
---
- @kashishshah
> fix: the case of multiple L2 batches in the same L1 block

- network/client.go
- rpcclient/arbitrum/batch_fetcher.go
- rpcclient/optimism/batch_fetcher.go
> fix: more robust fetcher stop logic

- network/client.go
> chore: minor error message updates

- crypto/merkle.go
- crypto/merkle_test.go
- docker-compose.yml
> chore: docker compose version fix

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- docker-compose.yml
- Add issue template for bug report and feature request
> add issue templates

- cmd/baseapp/main.go
- config/default.go
- docker-compose.yml
- network/client.go
- telemetry/metrics.go
Closes: #460 
- Updated the metrics config to manage the prometheus server port
- Fixed the stuck issue of the client
- Checked the zero committee root
---
- @mastereng12
> chore: update the metrics config

- store/mongodb/migrations/0001_template.go
- store/mongodb/migrations/0002_add_operators_field.go
- store/mongodb/migrations/init.go
Closes: #467 
- Add migration scripts and tested in devnet
---
> feat: add operators array fields to finalized batches

- client/client.go
- client/client_test.go
- client/rpc.go
- client/verifier.go
Closes: #487 
---
- @kashishshah
> feat: implement the verifier for the client

- client/verifier.go
- docker-compose.yml
Closes: #496
---
- @kashishshah
> chore: local network fix

- sequencer/sequencer.go
Closes: #XXXX
---
- @mastereng12
> [FIX] Epoch event conflict

- rpcclient/arbitrum/batch_fetcher.go
> chore: batch fetcher bug fix

- rpcclient/arbitrum/batch_fetcher.go
- rpcclient/arbitrum/client.go
- rpcclient/arbitrum/client_test.go
- rpcclient/arbitrum/config.go
- rpcclient/evmclient/evm_test.go
- rpcclient/evmclient/evmclient.go
- rpcclient/mantle/client.go
- rpcclient/mantle/config.go
- rpcclient/mock/client.go
- rpcclient/mock/config.go
- rpcclient/optimism/batch_fetcher.go
- rpcclient/optimism/client.go
- rpcclient/optimism/client_test.go
- rpcclient/optimism/config.go
- sequencer/sequencer_test.go
> feat: allow switching of multiple providers

- client/client_test.go
- client/rpc.go
- client/verifier.go
- rpcclient/evmclient/evmclient.go
- rpcclient/mock/client.go
- rpcclient/types/interface.go
- sequencer/types/v2/batch.go
- store/mongodb/convert.go
- store/mongodb/convert_test.go
> refactor: the batch verification logic on client

- store/mongodb/migrations/0003_add_l2_blocks_range.go
- store/mongodb/migrations/init.go
> implement db update to add from/to l2 blocks fields

- client/client.go
- client/client_test.go
- client/rpc.go
- client/verifier.go
- rpcclient/optimism/batch_decoder.go
- sequencer/types/v2/batch.go
- sequencer/types/v2/batch_test.go
- tests/integration/client_test.go
> refactor the batch hash

- sequencer/sequencer.go
- store/mongodb/convert.go
> fix: the minor sequencer bug

- store/mongodb/migrations/0003_add_l2_blocks_range.go
> fix minor bug in migrate script

- Makefile
- client/config.go
- client/signer.go
- cmd/baseapp/main.go
- core/cert.go
- docker-compose.yml
- signer/config.go
- signer/service.go
- testutil/chainconfig/cmd/main.go
- testutil/vector/ext.conf
- testutil/vector/generator.sh
Closes: #544
---
- @kashishshah
> secure tls communication of signer

- client/client.go
- client/signer.go
- client/verifier.go
- consensus/state.go
- consensus/types/round_state.go
- consensus/types/round_state_test.go
- core/crypto/bls.go
- core/crypto/bls12381.go
- core/crypto/bls_test.go
- core/crypto/bn254.go
- core/crypto/keystore.go
- server/service.go
- server/service_test.go
- signer/awskms/client.go
- signer/awskms/client_test.go
- signer/local/provider.go
- signer/local/provider_test.go
- signer/service.go
- signer/signer.go
- signer/signer_test_suite.go
ref: https://github.com/Lagrange-Labs/lsc-client-cli/issues/118
- added the missing telemetry metrics
---
- @kashishshah
> feat: add the g2 based bls scheme

- client/client.go
- client/client_test.go
- client/rpc.go
- rpcclient/arbitrum/client.go
- rpcclient/arbitrum/client_test.go
- rpcclient/mantle/client.go
- rpcclient/mock/client.go
- rpcclient/optimism/batch_decoder.go
- rpcclient/optimism/batch_fetcher.go
- rpcclient/optimism/client.go
- rpcclient/optimism/client_test.go
- rpcclient/types/interface.go
- sequencer/config.go
- sequencer/sequencer.go
Closes: #551 
---
- @kashishshah
> feat: refactor the optimism rpc client for polymer

- client/client.go
- sequencer/types/v2/batch.go
- server/service.go
- Update the batch hash to use the merkle hash of blocks
- Update the compatible version
---
- @kashishshah
> feat: update the batch hash as merkle

- rpcclient/client.go
Closes: #XXXX
---
- @kashishshah
> chore: add polymer option in rpc

- rpcclient/optimism/batch_fetcher.go
> fix: optimism empty frames

- config/default.go
- rpcclient/optimism/batch_decoder.go
- rpcclient/optimism/batch_fetcher.go
- rpcclient/optimism/client.go
- rpcclient/optimism/config.go
> fix: the method to get the L2BlockNumber

- rpcclient/optimism/batch_fetcher.go
- rpcclient/optimism/client_test.go
- rpcclient/optimism/config.go
- sequencer/sequencer_test.go
> refactor the config with multiple batch senders

- config/default.go
- rpcclient/optimism/batch_decoder.go
> fix the typo issue on optimism

- client/client.go
> chore: fix the client node version

- rpcclient/optimism/batch_fetcher.go
> feat: refactor the opt rpc

- rpcclient/arbitrum/batch_fetcher.go
> feat: add the light get batch api on Arbitrum rpc client

- client/client_test.go
- rpcclient/arbitrum/client.go
- rpcclient/mantle/client.go
- rpcclient/mock/client.go
- rpcclient/optimism/client.go
- rpcclient/types/interface.go
> feat: update the rpc client interface

- rpcclient/optimism/batch_fetcher.go
revert the minor compability breaking issue on Optimism rpc client
---
> fix: breaking the compability

- client/verifier.go
> feat: parallelize the client L2 blocks verification

- rpcclient/optimism/batch_decoder.go
- rpcclient/optimism/batch_fetcher.go
> feat: reduce the optimism calls in light mode

- client/verifier.go
- rpcclient/arbitrum/batch_fetcher.go
- rpcclient/optimism/batch_fetcher.go
> feat: refactor the light client to verify based on the last block

- Dockerfile
> chore: fix docker image build

- .github/pull_request_template.md
- go.mod
- go.sum
- signer/go.mod
- signer/go.sum
> chore: bump the core module to v0.1.2

- client/verifier.go
- go.mod
- go.sum
- rpcclient/mock/client.go
> fix: the local testnet

- client/rpc.go
- rpcclient/optimism/batch_decoder.go
- rpcclient/optimism/batch_fetcher.go
> fix: the batch fetching in the case of multiple L1 blocks on the optimism
